# Generated by Django 5.1.6 on 2025-03-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0219_remove_jira_project_enabled_and_more'),
        ('dojo', '0222_clean_old_sessions'),
    ]

    operations = [
    ]
