# Generated by Django 5.1.6 on 2025-03-21 08:12

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0226_finding_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_assessment',
            name='threat_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Spoofing'), ('T', 'Tampering'), ('R', 'Repudiation'), ('I', 'Information Disclosure'), ('D', 'Denial of Service'), ('E', 'Elevation of Privilege')], max_length=1000),
        ),
    ]
