# Generated by Django 5.1.6 on 2025-03-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0227_alter_risk_assessment_threat_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='risk',
        ),
    ]
