# Generated by Django 5.1.6 on 2025-03-25 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0229_finding_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dojo.risk_assessment'),
        ),
    ]
