# Generated by Django 5.1.6 on 2025-03-25 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0231_alter_finding_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='risk',
        ),
    ]
