# Generated by Django 5.1.6 on 2025-03-26 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0233_alter_risk_assessment_threat_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_File_Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_file_path', models.CharField(max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_paths', to='dojo.product')),
            ],
        ),
    ]
