# Generated by Django 5.1.7 on 2025-03-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0223_aws_sechub_update_endpoints'),
        ('dojo', '0234_product_file_path'),
    ]

    operations = [
    ]
