# Generated by Django 5.1.7 on 2025-03-28 11:03

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0235_merge_20250328_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk_assessment',
            name='threat_types',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('S', 'Spoofing'), ('T', 'Tampering'), ('R', 'Repudiation'), ('I', 'Information Disclosure'), ('D', 'Denial of Service'), ('E', 'Elevation of Privilege')], max_length=5000, null=True),
        ),
    ]
